name: check-crlf
author: erclu
description: "Checks for non-binary files with CRLF endings in given path"

branding:
  icon: file-text
  color: gray-dark

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.path }}
    - ${{ inputs.exclude }}

inputs:
  path:
    description: Path to check, separated with "/"
    required: false
    default: "."
  exclude:
    description: Space-separated list of words to exclude
    required: false
    default: ""
